services:
    httpsvr1:
        proto: http
        net:
            addr: :6443
            tls_crt_file: /tmp/etc/cert.pem
            tls_key_file: /tmp/etc/cert.key
        http:
            max_conns:              4
            dial_timeout:           10s
            response_timeout:       10s
            keepalive_timeout:      120s
            flush_interval:         10ms
            global_flush_interval:  10ms
            hijacks:
                - /board:   ums
                - /janus:   janus
            routes:
                - /test:    http://127.0.0.1:8080
                - /out:     http://127.0.0.1:8080
                - /janus:   http://127.0.0.1:8088

    tcpsvr1:
        proto: tcp
        net:
            addr: :6080
            tls_crt_file: /tmp/etc/cert.pem
            tls_key_file: /tmp/etc/cert.key
            ips:
                - 101.132.177.1
        enable_http: true
        http:
            max_conns:              4
            dial_timeout:           10s
            response_timeout:       10s
            keepalive_timeout:      120s
            flush_interval:         10ms
            global_flush_interval:  10ms
            hijacks:
                - /board:   ums
                - /janus:   janus
            routes:
                - /test:    http://127.0.0.1:8080
                - /out:     http://127.0.0.1:8080
                - /janus:   http://127.0.0.1:8088

    udpsvr1:
        proto: udp
        net:
            addr: :6000
            tls_crt_file: /tmp/etc/cert.pem
            tls_key_file: /tmp/etc/cert.key
            ips:
                - 101.132.177.1

